package my.workflow.storage.mysql.model;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

public class ProcessInstanceDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_instance.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_instance.process_id
     *
     * @mbg.generated
     */
    private String processId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_instance.factory
     *
     * @mbg.generated
     */
    private String factory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_instance.factory_material
     *
     * @mbg.generated
     */
    private String factoryMaterial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_instance.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_instance.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_instance.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_instance.runtime_data
     *
     * @mbg.generated
     */
    private String runtimeData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_instance.id
     *
     * @return the value of process_instance.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    public ProcessInstanceDO withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_instance.id
     *
     * @param id the value for process_instance.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_instance.process_id
     *
     * @return the value of process_instance.process_id
     *
     * @mbg.generated
     */
    public String getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    public ProcessInstanceDO withProcessId(String processId) {
        this.setProcessId(processId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_instance.process_id
     *
     * @param processId the value for process_instance.process_id
     *
     * @mbg.generated
     */
    public void setProcessId(String processId) {
        this.processId = processId == null ? null : processId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_instance.factory
     *
     * @return the value of process_instance.factory
     *
     * @mbg.generated
     */
    public String getFactory() {
        return factory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    public ProcessInstanceDO withFactory(String factory) {
        this.setFactory(factory);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_instance.factory
     *
     * @param factory the value for process_instance.factory
     *
     * @mbg.generated
     */
    public void setFactory(String factory) {
        this.factory = factory == null ? null : factory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_instance.factory_material
     *
     * @return the value of process_instance.factory_material
     *
     * @mbg.generated
     */
    public String getFactoryMaterial() {
        return factoryMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    public ProcessInstanceDO withFactoryMaterial(String factoryMaterial) {
        this.setFactoryMaterial(factoryMaterial);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_instance.factory_material
     *
     * @param factoryMaterial the value for process_instance.factory_material
     *
     * @mbg.generated
     */
    public void setFactoryMaterial(String factoryMaterial) {
        this.factoryMaterial = factoryMaterial == null ? null : factoryMaterial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_instance.status
     *
     * @return the value of process_instance.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    public ProcessInstanceDO withStatus(Integer status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_instance.status
     *
     * @param status the value for process_instance.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_instance.gmt_create
     *
     * @return the value of process_instance.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    public ProcessInstanceDO withGmtCreate(Date gmtCreate) {
        this.setGmtCreate(gmtCreate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_instance.gmt_create
     *
     * @param gmtCreate the value for process_instance.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_instance.gmt_modified
     *
     * @return the value of process_instance.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    public ProcessInstanceDO withGmtModified(Date gmtModified) {
        this.setGmtModified(gmtModified);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_instance.gmt_modified
     *
     * @param gmtModified the value for process_instance.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_instance.runtime_data
     *
     * @return the value of process_instance.runtime_data
     *
     * @mbg.generated
     */
    public String getRuntimeData() {
        return runtimeData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    public ProcessInstanceDO withRuntimeData(String runtimeData) {
        this.setRuntimeData(runtimeData);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_instance.runtime_data
     *
     * @param runtimeData the value for process_instance.runtime_data
     *
     * @mbg.generated
     */
    public void setRuntimeData(String runtimeData) {
        this.runtimeData = runtimeData == null ? null : runtimeData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", processId=").append(processId);
        sb.append(", factory=").append(factory);
        sb.append(", factoryMaterial=").append(factoryMaterial);
        sb.append(", status=").append(status);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", runtimeData=").append(runtimeData);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        processId("process_id", "processId", "VARCHAR", false),
        factory("factory", "factory", "VARCHAR", false),
        factoryMaterial("factory_material", "factoryMaterial", "VARCHAR", false),
        status("status", "status", "INTEGER", false),
        gmtCreate("gmt_create", "gmtCreate", "TIMESTAMP", false),
        gmtModified("gmt_modified", "gmtModified", "TIMESTAMP", false),
        runtimeData("runtime_data", "runtimeData", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table process_instance
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table process_instance
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table process_instance
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table process_instance
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table process_instance
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table process_instance
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table process_instance
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table process_instance
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table process_instance
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table process_instance
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table process_instance
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table process_instance
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table process_instance
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table process_instance
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table process_instance
         *
         * @mbg.generated
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table process_instance
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table process_instance
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}