package my.workflow.storage.mysql.dao;

import java.util.List;
import my.workflow.storage.mysql.model.ProcessInstanceDO;
import my.workflow.storage.mysql.model.ProcessInstanceDOExample;
import org.apache.ibatis.annotations.Param;

public interface ProcessInstanceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    long countByExample(ProcessInstanceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    int deleteByExample(ProcessInstanceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    int insert(ProcessInstanceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    int insertSelective(ProcessInstanceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    ProcessInstanceDO selectOneByExample(ProcessInstanceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    ProcessInstanceDO selectOneByExampleWithBLOBs(ProcessInstanceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    List<ProcessInstanceDO> selectByExampleWithBLOBs(ProcessInstanceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    List<ProcessInstanceDO> selectByExample(ProcessInstanceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    ProcessInstanceDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProcessInstanceDO record, @Param("example") ProcessInstanceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ProcessInstanceDO record, @Param("example") ProcessInstanceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProcessInstanceDO record, @Param("example") ProcessInstanceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProcessInstanceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ProcessInstanceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProcessInstanceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<ProcessInstanceDO> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<ProcessInstanceDO> list, @Param("selective") ProcessInstanceDO.Column ... selective);
}